project:
  type: website
  output-dir: docs

website:
  title: "Daianna Gonzalez-Padilla"
  site-url: https://daianna21.github.io/daianna_blog/
  description: "Daianna's personal scientific blog"
  favicon: "images/logo-removebg.png"
  navbar:
    right:
      - text: "About me"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - icon: github
        href: https://daianna21.github.io
      - icon: linkedin
        href: http://www.linkedin.com/in/daianna-glez
      - icon: twitter
        href: https://x.com/daianna_glez/
      - icon: envelope-at
        href: mailto:glezdaianna@gmail.com
      - icon: rss
        href: blog.xml
  comments:
    giscus: 
      repo: lahuuki/lahuuki.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

